import { safeDivide } from "../../accounting/numeric.js";

export const FINANCE_METRICS = {
  cash_balance: { domain: "finance", key: "cash_balance", label: "Cash Balance", formula: "SUM(cash)", outputType: "currency", required: [["cash"]], safetyLevel: "normal", calculate: ({ sums }) => ({ value: sums.cash }) },
  cash_flow: { domain: "finance", key: "cash_flow", label: "Cash Flow", formula: "SUM(cash_in)-SUM(cash_out)", outputType: "currency", required: [["cash_in","cash_out"],["cash"]], safetyLevel: "normal", calculate: ({ sums, headersUsed }) => ({ value: headersUsed.cash ? sums.cash : sums.cash_in - sums.cash_out }) },
  working_capital: { domain: "finance", key: "working_capital", label: "Working Capital", formula: "current_assets-current_liabilities", outputType: "currency", required: [["current_assets","current_liabilities"]], safetyLevel: "normal", calculate: ({ sums }) => ({ value: sums.current_assets - sums.current_liabilities }) },
  current_ratio: { domain: "finance", key: "current_ratio", label: "Current Ratio", formula: "current_assets/current_liabilities", outputType: "number", required: [["current_assets","current_liabilities"]], safetyLevel: "normal", calculate: ({ sums }) => { const d = safeDivide(sums.current_assets, sums.current_liabilities); return d.ok ? { value: d.value } : { value: null, note: "Current liabilities denominator is zero" }; } },
  quick_ratio: { domain: "finance", key: "quick_ratio", label: "Quick Ratio", formula: "(current_assets-inventory)/current_liabilities", outputType: "number", required: [["current_assets","inventory","current_liabilities"]], safetyLevel: "normal", calculate: ({ sums }) => { const d = safeDivide(sums.current_assets - sums.inventory, sums.current_liabilities); return d.ok ? { value: d.value } : { value: null, note: "Current liabilities denominator is zero" }; } },
  debt_to_equity: { domain: "finance", key: "debt_to_equity", label: "Debt to Equity", formula: "debt/equity", outputType: "number", required: [["debt","equity"]], safetyLevel: "advisory_sensitive", calculate: ({ sums }) => { const d = safeDivide(sums.debt, sums.equity); return d.ok ? { value: d.value } : { value: null, note: "Equity denominator is zero" }; } },
};
