export const COMPLEX_QUESTION_REQUIREMENTS = {
  driver_analysis_profit: {
    questionType: "driver_analysis_profit",
    primaryMetric: "net_income",
    minimumRequiredFieldSets: [["net_income", "date"], ["revenue", "expenses", "date"]],
    optionalFields: ["cogs", "gross_profit", "gross_margin_pct", "discounts", "returns", "payroll", "category", "account", "department", "store", "region"],
    supportedSteps: ["calculate_metric", "calculate_variance", "rank_drivers", "detect_top_changes"],
    partialAnswerRules: "allow_high_level_if_minimum_present",
    missingFieldRecommendations: ["revenue", "expenses", "cogs", "discounts", "returns", "category", "account"],
  },
  driver_analysis_gross_margin: {
    questionType: "driver_analysis_gross_margin",
    primaryMetric: "gross_margin_pct",
    minimumRequiredFieldSets: [["revenue", "cogs", "date"], ["gross_profit", "revenue", "date"]],
    optionalFields: ["product_category", "category", "store", "region", "discounts", "returns"],
    supportedSteps: ["calculate_metric", "calculate_variance", "summarize_by_group"],
    partialAnswerRules: "allow_high_level_if_minimum_present",
    missingFieldRecommendations: ["cogs", "product_category", "discounts", "returns"],
  },
  driver_analysis_expenses: {
    questionType: "driver_analysis_expenses",
    primaryMetric: "total_expense",
    minimumRequiredFieldSets: [["expenses", "date"]],
    optionalFields: ["category", "account", "department", "vendor", "payroll", "store", "region"],
    supportedSteps: ["calculate_metric", "calculate_variance", "rank_drivers"],
    partialAnswerRules: "allow_high_level_if_minimum_present",
    missingFieldRecommendations: ["category", "account", "department", "vendor"],
  },
  period_comparison_revenue: {
    questionType: "period_comparison_revenue",
    primaryMetric: "total_revenue",
    minimumRequiredFieldSets: [["revenue", "date"]],
    optionalFields: ["store", "region", "category", "customer"],
    supportedSteps: ["compare_periods", "calculate_variance", "calculate_percentage_change"],
    partialAnswerRules: "allow_high_level_if_minimum_present",
    missingFieldRecommendations: ["store", "region", "category", "customer"],
  },
  pnl_summary: {
    questionType: "pnl_summary",
    primaryMetric: "net_income",
    minimumRequiredFieldSets: [["revenue", "expenses"], ["net_income"], ["revenue", "cogs", "expenses"]],
    optionalFields: ["date", "cogs", "gross_profit", "gross_margin_pct", "operating_expenses", "payroll", "category", "account", "department"],
    supportedSteps: ["calculate_metric", "calculate_ratio", "summarize_by_group"],
    partialAnswerRules: "allow_partial",
    missingFieldRecommendations: ["cogs", "gross_profit", "gross_margin_pct", "account", "department"],
  },
  budget_vs_actual: {
    questionType: "budget_vs_actual",
    primaryMetric: "variance_amount",
    minimumRequiredFieldSets: [["actual", "budget"]],
    optionalFields: ["date", "category", "account", "department", "store", "region"],
    supportedSteps: ["calculate_metric", "calculate_variance", "rank_drivers"],
    partialAnswerRules: "allow_high_level_if_minimum_present",
    missingFieldRecommendations: ["department", "category", "account", "date"],
  },
  cash_flow_issue: {
    questionType: "cash_flow_issue",
    primaryMetric: "unknown",
    minimumRequiredFieldSets: [["cash", "date"], ["cash_in", "cash_out", "date"], ["accounts_receivable", "accounts_payable", "date"]],
    optionalFields: ["customer", "vendor", "category", "account"],
    supportedSteps: ["compare_periods", "summarize_by_group", "detect_top_changes"],
    partialAnswerRules: "allow_partial",
    missingFieldRecommendations: ["cash", "cash_in", "cash_out", "accounts_receivable", "accounts_payable"],
  },
};
